# Generated by Django 4.1.4 on 2022-12-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('patientId', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
